#!/bin/bash
# scripts/migrate-secrets.sh
# Export secrets from Cloudflare Workers and import to VM .env file.
# Usage: bash scripts/migrate-secrets.sh [--dry-run]
#
# Prerequisites:
#   - wrangler CLI authenticated (npx wrangler whoami)
#   - SSH or local access to the target VM
#
# This script enumerates CF Worker secrets and writes them to the VM's
# .env file at /opt/moltworker/.env. It never echoes secret values.

set -e

DRY_RUN=false
ENV_FILE="/opt/moltworker/.env"

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --env-file=*) ENV_FILE="${arg#*=}" ;;
    *) echo "Unknown arg: $arg"; exit 1 ;;
  esac
done

echo "=== Moltworker Secret Migration ==="
echo "Target: $ENV_FILE"
echo "Dry run: $DRY_RUN"
echo ""

# --- Secrets mapping ---
# CF Worker secret name -> VM .env variable name
# Some secrets are renamed during migration (e.g., MOLTBOT_GATEWAY_TOKEN -> OPENCLAW_GATEWAY_TOKEN)
declare -A SECRET_MAP=(
  # AI Provider
  ["AI_GATEWAY_API_KEY"]="AI_GATEWAY_API_KEY"
  ["AI_GATEWAY_BASE_URL"]="AI_GATEWAY_BASE_URL"
  ["AI_GATEWAY_MODEL"]="AI_GATEWAY_MODEL"
  ["ANTHROPIC_API_KEY"]="ANTHROPIC_API_KEY"
  ["OPENAI_API_KEY"]="OPENAI_API_KEY"
  ["CLOUDFLARE_AI_GATEWAY_API_KEY"]="CLOUDFLARE_AI_GATEWAY_API_KEY"
  ["CF_AI_GATEWAY_ACCOUNT_ID"]="CF_AI_GATEWAY_ACCOUNT_ID"
  ["CF_AI_GATEWAY_GATEWAY_ID"]="CF_AI_GATEWAY_GATEWAY_ID"

  # Authentication — rename MOLTBOT -> OPENCLAW
  ["MOLTBOT_GATEWAY_TOKEN"]="OPENCLAW_GATEWAY_TOKEN"

  # Mentra
  ["MENTRA_API_KEY"]="MENTRA_API_KEY"

  # Cloudflare Access (used by verify-access.sh and middleware)
  ["CF_ACCESS_TEAM_DOMAIN"]="CF_ACCESS_TEAM_DOMAIN"
  ["CF_ACCESS_AUD"]="CF_ACCESS_AUD"

  # Chat channels (optional)
  ["TELEGRAM_BOT_TOKEN"]="TELEGRAM_BOT_TOKEN"
  ["DISCORD_BOT_TOKEN"]="DISCORD_BOT_TOKEN"
  ["SLACK_BOT_TOKEN"]="SLACK_BOT_TOKEN"
  ["SLACK_APP_TOKEN"]="SLACK_APP_TOKEN"

  # R2 credentials (needed for migrate-r2-to-local.sh)
  ["R2_ACCESS_KEY_ID"]="R2_ACCESS_KEY_ID"
  ["R2_SECRET_ACCESS_KEY"]="R2_SECRET_ACCESS_KEY"
  ["CF_ACCOUNT_ID"]="CF_ACCOUNT_ID"
)

# --- Step 1: Enumerate current CF Worker secrets ---
echo "Listing Cloudflare Worker secrets..."
CF_SECRETS=$(npx wrangler secret list --json 2>/dev/null || echo "[]")

if [ "$CF_SECRETS" = "[]" ]; then
  echo "WARNING: No secrets found (wrangler may not be authenticated)"
  echo "You can still manually populate $ENV_FILE using .env.example as a template."
  exit 0
fi

# Extract secret names from JSON array
CF_SECRET_NAMES=$(echo "$CF_SECRETS" | node -e "
  const data = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
  data.forEach(s => console.log(s.name));
")

echo "Found CF Worker secrets:"
echo "$CF_SECRET_NAMES" | while read -r name; do
  echo "  - $name"
done
echo ""

# --- Step 2: Build .env file ---
if [ "$DRY_RUN" = true ]; then
  echo "[DRY RUN] Would write to $ENV_FILE:"
  echo ""
fi

ENV_CONTENT="# /opt/moltworker/.env
# Auto-generated by migrate-secrets.sh on $(date -Iseconds)
# Migrated from Cloudflare Workers secrets
#
# IMPORTANT: This file contains secrets. Do not commit to version control.
# Permissions should be 600 (owner read/write only).
"

MIGRATED=0
SKIPPED=0

for cf_name in "${!SECRET_MAP[@]}"; do
  vm_name="${SECRET_MAP[$cf_name]}"

  if echo "$CF_SECRET_NAMES" | grep -q "^${cf_name}$"; then
    # Secret exists in CF — prompt for value (wrangler cannot export values)
    ENV_CONTENT+="
# Migrated from CF Worker secret: $cf_name
${vm_name}="
    MIGRATED=$((MIGRATED + 1))
  else
    SKIPPED=$((SKIPPED + 1))
  fi
done

# --- Step 3: Add VM-only variables (not in CF Workers) ---
ENV_CONTENT+="

# --- VM-only configuration (not from CF Workers) ---

# Alert webhook for health-check.sh (Discord or Slack incoming webhook URL)
# ALERT_WEBHOOK_URL=

# Moltworker domain (used by verify-access.sh)
# MOLTWORKER_DOMAIN=moltworker.example.com
"

if [ "$DRY_RUN" = true ]; then
  echo "$ENV_CONTENT"
  echo ""
  echo "--- Summary ---"
  echo "Secrets to migrate: $MIGRATED"
  echo "Secrets not found in CF (skipped): $SKIPPED"
  echo ""
  echo "NOTE: wrangler cannot export secret values. After generating the .env file,"
  echo "you must manually fill in each value from your password manager or CF dashboard."
  exit 0
fi

# --- Step 4: Write .env file ---
mkdir -p "$(dirname "$ENV_FILE")"

if [ -f "$ENV_FILE" ]; then
  BACKUP="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  echo "Backed up existing .env to $BACKUP"
fi

echo "$ENV_CONTENT" > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo ""
echo "=== Migration Summary ==="
echo "Secrets mapped: $MIGRATED"
echo "Secrets not found (skipped): $SKIPPED"
echo "Output: $ENV_FILE (permissions: 600)"
echo ""
echo "NEXT STEPS:"
echo "  1. Fill in secret values in $ENV_FILE"
echo "     (wrangler cannot export values — use your password manager)"
echo "  2. Run: bash scripts/openclaw-config.sh"
echo "  3. Run: pm2 start ecosystem.config.js"
